"""added temp column for testing

Revision ID: dde21ff18b1a
Revises: None
Create Date: 2016-01-14 19:30:15.072102

"""

# revision identifiers, used by Alembic.
revision = 'dde21ff18b1a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp')
    ### end Alembic commands ###
